server:
  port: 8082

spring:
  application:
    name: producer-schedules-buses-red
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

rabbitmq:
  exchange:
    schedules: schedules.exchange
  queue:
    schedules: schedules.queue
  routing-key:
    schedules: schedules.routing.key

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.busesred: DEBUG
    org.springframework.amqp: DEBUG
